version: '3'
services:
  sandbox:
    build:
      context: .
      #command: tail -f /dev/null
    volumes:
      #- .:/code
      #- ./dapps/chainlink:/usr/src/app
      - ./dapps/hackathon:/usr/src/app/hackathon
    env_file:
      - .env
