---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainlink-api
  namespace: fraxses-sandbox-env
spec:
  replicas: 1
  selector:
    matchLabels:
      component: chainlink-api
  template:
    metadata:
      labels:
        component: chainlink-api
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: fraxses-reg-cred
      containers:
        - name: chainlink-api-img
          imagePullPolicy: Always
          image: 'registry.fraxses.com/project/chainlink/brownie:001'
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: fraxses-kf-svc-headless:9092
            - name: FRAXSES_CLIENT_SECRET
              value: kZXem8W4SVAwOHRi8qTn
            - name: ENVIRONMENT
              value: development
            - name: WEB3_INFURA_PROJECT_ID           
              value: f676be44277e45c898f17a2cb8e3a1ab 
            - name: WEB3_INFURA_PROJECT_SECRET 
              value: 3301cb50d3ff4e4989d48d9af9e4e2f3
            - name: WEB3_INFURA_MAINNET_WSS
              value: wss://mainnet.infura.io/ws/v3/f676be44277e45c898f17a2cb8e3a1ab
            - name: WEB3_INFURA_MAINNET_HTTPS
              value: https://mainnet.infura.io/v3/f676be44277e45c898f17a2cb8e3a1ab
            - name: WEB3_INFURA_KOVAN_WSS
              value: wss://kovan.infura.io/ws/v3/f676be44277e45c898f17a2cb8e3a1ab              
            - name: WEB3_INFURA_KOVAN_HTTPS
              value: https://kovan.infura.io/v3/f676be44277e45c898f17a2cb8e3a1ab
            - name: WALLET_PRIVATE_KEY_MAINNET
              value: XXX-YYY-ZZZ
            - name: WALLET_PRIVATE_KEY_KOVAN
              value: 5f1bf226abf98c9dad8a4b6651dcce76e394d2adfddaac423b829f5949dccc2a 
            - name: ETHERSCAN_TOKEN
              value: RFGDAMVV5FN3FPMKQRCGUC5HDIDQE9W2KJ
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          resources:
            requests:
              memory: 1000Mi
              cpu:  1500m
          volumeMounts:
            - name: fraxses-shared-vm
              mountPath: /var/fraxses/shared/chainlink
