apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: chainlink-node-pool
  name: azure-load-balancer
spec:
  loadBalancerIP: 20.84.51.214 # This will change per deplyment
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/instance: zany-seat
    app.kubernetes.io/name: postgresql
