import os

ENVIRONMENT =  os.environ.get('ENVIRONMENT', 'dev')
WEB3_INFURA_PROJECT_ID = os.environ.get('INFURA_PROJECT_ID', '')            
WEB3_INFURA_PROJECT_SECRET = os.environ.get('INFURA_PROJECT_SECRET', '')
WEB3_INFURA_MAINNET_WSS = os.environ.get('INFURA_MAINNET_WSS', '')
WEB3_INFURA_MAINNET_HTTPS = os.environ.get('INFURA_MAINNET_HTTPS', '')
WEB3_INFURA_KOVAN_WSS = os.environ.get('INFURA_KOVAN_WSS', '')
WEB3_INFURA_KOVAN_HTTPS = os.environ.get('INFURA_KOVAN_HTTPS', '')
WALLET_PRIVATE_KEY_MAINNET = os.environ.get('WALLET_PRIVATE_KEY_MAINNET', '') 
WALLET_PRIVATE_KEY_KOVAN =  os.environ.get('WALLET_PRIVATE_KEY_KOVAN', '')
PRIVATE_KEY = WALLET_PRIVATE_KEY_KOVAN
ETHERSCAN_TOKEN = os.environ.get('ETHERSCAN_TOKEN','')
